version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - app-network

    node:
        build:
            context: .
            dockerfile: Dockerfile.node
        container_name: vue_app
        restart: unless-stopped
        ports:
            - "5173:5173" # Updated port mapping to match Vue default
        volumes:
            - .:/usr/src/app
        depends_on:
            - app
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app-network

volumes:
    mysql-data:

networks:
    app-network:
        driver: bridge
